const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const cardsDir = path.join(__dirname, 'cards');
const imagesDir = path.join(root, 'images');
fs.mkdirSync(cardsDir, { recursive: true });
fs.mkdirSync(imagesDir, { recursive: true });

const posts = [
  ["Your Back Office Is Stealing Selling Time", "Manual portal work pulls your best people away from customers.", "Awareness", "VidaPay and Total Wireless retailers should not have to choose between serving customers and finishing repetitive back-office work. When reporting, ordering, and claims consume the day, selling time disappears. 3SVerse helps turn those repeatable workflows into guided, consistent processes—on the Windows PCs your team already uses.\n\nStart by identifying the task your team repeats most. Then give that time back to the store.", "Explore the tools at 3sverse.com", "#VidaPay #TotalWireless #WirelessRetail #RetailAutomation #DealerOperations"],
  ["One Dealer Login. Too Many Repetitive Steps.", "The portal is essential. Repeating the same clicks is not.", "Pain Point", "VidaPay is central to daily operations, but extracting records, ordering devices, and filing rebates can still demand the same clicks again and again. 3SVerse adds a practical automation layer while your team continues working under its own authorized login.\n\nLess repetition. More consistent execution. More time for customers.", "See the workflow suite at 3sverse.com", "#VidaPay #WirelessDealer #RetailOperations #WorkflowAutomation #3SVerse"],
  ["Multi-Store Growth Shouldn’t Multiply Admin", "More locations should create leverage—not more spreadsheets.", "Multi-Store", "Every new location adds orders, claims, reporting, and follow-up. Without a repeatable system, growth can multiply administrative work faster than revenue. 3SVerse is designed for multi-store wireless dealer operations, helping teams apply the same workflow across locations while retaining store-level visibility.\n\nBuild the operating rhythm before the next location opens.", "Start a free trial", "#MultiStoreRetail #TotalWireless #WirelessRetail #DealerOperations #RetailTech"],
  ["The Cost of One Missed IMEI", "Small data gaps can become expensive incentive gaps.", "Revenue Control", "A missed IMEI or incomplete incentive review can quietly reduce margin. The VidaPay Incentive Extractor helps dealers move portal data into a structured workbook and review performance at the transaction level.\n\nBetter visibility does not just save time—it supports better revenue control.", "Try the Incentive Extractor free", "#VidaPay #IncentiveManagement #WirelessDealer #RetailAnalytics #3SVerse"],
  ["Meet the VidaPay Workflow Suite", "Extract incentives. Order devices. File rebates.", "Suite", "Three recurring VidaPay workflows, one focused toolkit for wireless retailers: Incentive Extractor, Device Ordering, and Rebate Filing. Use the tool that solves today’s bottleneck or choose the full bundle for a more consistent back office.\n\nBuilt for practical daily use by VidaPay and Total Wireless dealer teams.", "Compare tools and plans at 3sverse.com", "#VidaPay #TotalWireless #RetailAutomation #WirelessRetail #3SVerse"],
  ["From Portal Data to Excel—Without the Copy/Paste", "Turn repeat extraction into a repeatable workflow.", "Incentive Extractor", "Copying portal records into spreadsheets is slow and easy to interrupt. The VidaPay Incentive Extractor organizes the workflow so dealer teams can produce usable Excel data with fewer manual steps.\n\nSpend less time rebuilding reports and more time acting on what they show.", "Start the free Windows trial", "#VidaPay #ExcelAutomation #WirelessRetail #RetailReporting #DealerOperations"],
  ["See Incentives at IMEI Level", "The detail you need to investigate exceptions faster.", "Incentive Extractor", "Store totals tell you what happened. IMEI-level detail helps you understand why. Give managers a clearer path to review incentive records, spot exceptions, and follow up with confidence.\n\nOperational visibility is strongest when the underlying transactions are easy to inspect.", "Explore Incentive Extractor", "#IncentiveManagement #VidaPay #WirelessDealer #RetailAnalytics #3SVerse"],
  ["One Dashboard for Every Store", "Keep location-level reporting organized as you scale.", "Incentive Extractor", "Multi-store operators need a portfolio view without losing store-level accountability. 3SVerse helps organize VidaPay extraction across locations so results are easier to compare, review, and share.\n\nA consistent report can become a consistent management habit.", "See multi-store options at 3sverse.com", "#MultiStoreRetail #VidaPay #RetailReporting #WirelessRetail #Operations"],
  ["Stop Rebuilding the Same Report", "If a report repeats, the process should improve each time.", "Incentive Extractor", "Weekly and monthly reporting should not start from zero. Standardize the extraction routine, reduce copy-and-paste work, and give your team an output they know how to use.\n\nRepeatable work deserves a repeatable tool.", "Try it free", "#WorkflowAutomation #VidaPay #WirelessDealer #RetailProductivity #3SVerse"],
  ["Your Data. Your Workflow. Your Decision.", "Test the workflow in your real operation—no card required.", "Free Trial", "The best way to evaluate automation is with the work your team already does. Install the VidaPay Incentive Extractor on Windows, run it under your own authorized login, and judge the time saved in your own stores.\n\nThe trial is free for 7 days and does not require a payment card.", "Start at 3sverse.com", "#VidaPay #FreeTrial #WirelessRetail #RetailAutomation #3SVerse"],
  ["Ordering Shouldn’t Consume Your Shift", "Give recurring device orders a faster, cleaner process.", "Device Ordering", "Device ordering is important—but repeated product selection and store-by-store entry can consume hours. 3SVerse Device Ordering guides the workflow so teams can prepare and submit orders more consistently across locations.\n\nMake ordering day predictable again.", "Try Device Ordering free", "#DeviceOrdering #VidaPay #TotalWireless #InventoryManagement #WirelessRetail"],
  ["Right Product. Right Store. Right Quantity.", "Reduce avoidable ordering mistakes before submission.", "Device Ordering", "A clean order depends on three things: the correct product, the correct location, and the correct quantity. A guided workflow helps dealer teams review those choices before they become costly inventory problems.\n\nControl starts before the order is placed.", "Explore Device Ordering at 3sverse.com", "#InventoryManagement #WirelessDealer #RetailOperations #VidaPay #3SVerse"],
  ["One Guided Submit Across Branches", "Standardize the ordering routine for every location.", "Device Ordering", "When each store uses a different process, ordering becomes harder to review and support. 3SVerse gives multi-store teams a consistent path for preparing device orders across branches while preserving location-level choices.\n\nOne routine is easier to teach, repeat, and improve.", "See multi-store pricing", "#MultiStoreRetail #DeviceOrdering #TotalWireless #DealerOperations #RetailTech"],
  ["Reduce Ordering Errors Before They Cost You", "Fewer rushed clicks. Better review. Cleaner inventory decisions.", "Device Ordering", "Ordering errors can create stock imbalances, tied-up cash, and avoidable transfers between stores. A structured workflow helps your team slow down at the right moments and move faster everywhere else.\n\nAutomation is valuable when it improves both speed and control.", "Start a free trial", "#InventoryControl #VidaPay #WirelessRetail #RetailAutomation #3SVerse"],
  ["A Cleaner Weekly Ordering Routine", "Turn a stressful task into an operating cadence.", "Device Ordering", "The strongest dealer operations are built on routines teams can follow even during busy weeks. Standardize product selection, quantities, and store assignment so ordering becomes easier to execute and easier to review.\n\nConsistency is a competitive advantage.", "Explore the Device Ordering tool", "#RetailOperations #WirelessDealer #DeviceOrdering #ProcessImprovement #3SVerse"],
  ["Unfiled Rebates Are Revenue Left Behind", "Protect margin with a more visible claim workflow.", "Rebate Filing", "A completed sale is not the end of the revenue cycle when a rebate still needs to be filed. 3SVerse Rebate Filing helps dealer teams work through eligible claims in a structured process and keep better visibility on status.\n\nMake rebate follow-up part of the operating system—not a last-minute scramble.", "Try Rebate Filing free", "#RebateManagement #VidaPay #TotalWireless #WirelessDealer #RevenueOperations"],
  ["Bulk Claims Without Losing Claim-Level Visibility", "Move faster while keeping exceptions visible.", "Rebate Filing", "Bulk work should not mean blind work. A better rebate process helps teams handle volume while preserving the ability to see what was filed, what failed, and what still needs attention.\n\nSpeed matters. So does traceability.", "Explore Rebate Filing at 3sverse.com", "#RebateFiling #RetailAutomation #VidaPay #WirelessRetail #3SVerse"],
  ["Know What’s Pending, Filed, Failed", "Status clarity turns follow-up into action.", "Rebate Filing", "Claims become difficult to manage when status lives in memory, scattered notes, or multiple tabs. Use a consistent view of pending, completed, and failed work so the next action is clear.\n\nGood operations make exceptions visible early.", "Start the free Windows trial", "#RebateManagement #DealerOperations #TotalWireless #WorkflowAutomation #3SVerse"],
  ["Fewer Tabs. Fewer Missed Claims.", "Simplify the path from eligible sale to submitted rebate.", "Rebate Filing", "Constantly switching between tabs and records increases fatigue and the chance that an eligible claim is overlooked. A guided filing workflow reduces that friction and helps staff stay focused on completion.\n\nProtect attention—and protect earned revenue.", "See how Rebate Filing works", "#RetailProductivity #RebateFiling #VidaPay #WirelessDealer #3SVerse"],
  ["Turn Rebate Work Into a Repeatable Process", "A dependable routine beats a heroic monthly catch-up.", "Rebate Filing", "Rebate filing should not depend on one employee remembering every step. Create a routine that can be taught, tracked, and repeated across your stores. 3SVerse helps turn a recurring burden into a clearer operational process.\n\nSystems scale. Memory does not.", "Try it free", "#ProcessImprovement #RebateManagement #MultiStoreRetail #WirelessRetail #3SVerse"],
  ["Your Credentials Stay on Your PC", "Local-first automation for operational confidence.", "Security", "Retailers need efficiency without casually moving sensitive workflow data into another cloud. 3SVerse tools run on your Windows PC under your own authorized VidaPay login, with operational data kept locally.\n\nYou stay in control of the machine, the login, and the workflow.", "Read the security approach at 3sverse.com", "#DataPrivacy #VidaPay #RetailTechnology #WirelessDealer #3SVerse"],
  ["Built for Windows 10 & 11", "Use the PCs already running your stores.", "Compatibility", "Adoption is easier when a tool fits the existing environment. 3SVerse desktop tools are built for Windows 10 and 11, helping dealer teams improve back-office workflows without replacing their store technology stack.\n\nPractical software should meet operators where they work.", "Download the free trial", "#WindowsSoftware #WirelessRetail #RetailAutomation #DealerOperations #3SVerse"],
  ["When VidaPay Changes, Updates Are Included", "Automation should be maintained—not abandoned.", "Support", "Portal workflows evolve. The software supporting them needs to evolve too. Active 3SVerse licenses include updates, helping retailers stay aligned as supported workflows change. Same-day support is available when your team needs help.\n\nA tool is only useful when it keeps working in the real world.", "Review plans at 3sverse.com", "#VidaPay #SoftwareSupport #WirelessDealer #RetailTech #3SVerse"],
  ["Built by Operators, Not Outsiders", "Tools shaped by the repetitive work dealers actually face.", "Operator Focus", "The best workflow tools start with the details operators notice: repeated clicks, missed follow-up, inconsistent store processes, and hours lost to routine admin. 3SVerse focuses on those practical dealer pain points.\n\nIndependent software, built for VidaPay and Total Wireless retail workflows.", "Meet the toolkit at 3sverse.com", "#WirelessRetail #TotalWireless #DealerOperations #RetailAutomation #3SVerse"],
  ["What Is One Admin Hour Worth Across 5 Stores?", "Time savings compound across people, weeks, and locations.", "ROI", "One repetitive task may look small. Multiply it by five stores, several employees, and every week of the year—and the cost becomes visible. Automation creates leverage by returning those hours to sales, coaching, inventory, and customer service.\n\nMeasure the task once. Then calculate what repetition is costing you.", "Run your own time-saving test", "#RetailROI #MultiStoreRetail #WirelessDealer #Operations #3SVerse"],
  ["Multi-PC Discounts for Growing Dealer Groups", "Equip the operation—not just one desk.", "Scale", "Standardization works best when the right team members have access. 3SVerse offers volume discounts for multiple PCs: 10% for 2–4, 20% for 5–9, and custom pricing for 10 or more.\n\nCreate one operating standard across the dealer group.", "View multi-PC options at 3sverse.com", "#MultiStoreRetail #WirelessDealer #RetailTechnology #DealerOperations #3SVerse"],
  ["Monthly, Annual, or Lifetime—Choose Your Fit", "Match the software decision to your operating horizon.", "Pricing", "Some retailers want the flexibility of monthly software. Others prefer annual planning or a lifetime license. 3SVerse offers multiple ways to adopt individual tools or the full bundle, so dealers can choose the fit that matches their business.\n\nStart with the workflow creating the most friction today.", "Compare current plans at 3sverse.com", "#RetailSoftware #VidaPay #WirelessRetail #BusinessTools #3SVerse"],
  ["Three Workflows. One Operating System.", "Extract incentives, order devices, and file rebates with one suite.", "Full Bundle", "Back-office improvement is strongest when the workflows support one another. The 3SVerse Full Bundle brings together Incentive Extractor, Device Ordering, and Rebate Filing for VidaPay and Total Wireless dealer teams.\n\nOne toolkit. Three recurring pain points. A more consistent operation.", "Explore the Full Bundle", "#VidaPay #TotalWireless #RetailAutomation #WirelessDealer #3SVerse"],
  ["Money-Back Confidence", "Adopt with a clear safety net.", "Guarantee", "Software should earn its place in your operation. Alongside the free 7-day trial, eligible 3SVerse purchases include a 30-day money-back guarantee. Test the tools against real workflows and make the decision with evidence.\n\nNo inflated promises—just a practical opportunity to measure the fit.", "Review the guarantee and plans", "#RetailTechnology #WirelessDealer #SoftwareTrial #Operations #3SVerse"],
  ["Start Your Free Trial", "Choose the workflow that costs your team the most time.", "Call to Action", "For VidaPay and Total Wireless retailers, repetitive admin is not just inconvenient—it limits focus, consistency, and growth. Choose Incentive Extractor, Device Ordering, Rebate Filing, or the Full Bundle and test it in your real operation.\n\nWindows 10/11. No card required. Your login. Your PC. Your decision.", "Start now at 3sverse.com", "#VidaPay #TotalWireless #WirelessRetail #RetailAutomation #3SVerse"]
];

const esc = (s) => s.replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dateFmt = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
const phases = [
  {from:1,to:5,label:'Awareness & Pain',accent:'#ff6b2c',pos:'center'},
  {from:6,to:10,label:'Incentive Extractor',accent:'#06c9ef',pos:'left center'},
  {from:11,to:15,label:'Device Ordering',accent:'#6d75ff',pos:'center'},
  {from:16,to:20,label:'Rebate Filing',accent:'#d22bd8',pos:'right center'},
  {from:21,to:24,label:'Trust & Support',accent:'#26d7b5',pos:'center'},
  {from:25,to:27,label:'ROI & Scale',accent:'#ffab35',pos:'left center'},
  {from:28,to:30,label:'Conversion',accent:'#ee3f8f',pos:'right center'}
];

for (let i = 0; i < posts.length; i++) {
  const day = i + 1;
  const [headline, subhead, eyebrow, caption, cta, tags] = posts[i];
  const date = new Date(Date.UTC(2026, 9, day));
  const phase = phases.find(p => day >= p.from && day <= p.to);
  const headlineSize = headline.length > 46 ? 46 : headline.length > 34 ? 51 : 57;
  const art = day % 6 === 0 ? 'shape-v3.webp' : 'shape-v1.webp';
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>
*{box-sizing:border-box}html,body{margin:0;width:1200px;height:627px;overflow:hidden;font-family:"Segoe UI",Arial,sans-serif;background:#060509;color:#f4f1ed}.card{position:relative;width:1200px;height:627px;overflow:hidden;padding:35px 54px;background-color:#060509;background-image:linear-gradient(rgba(255,255,255,.026) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.026) 1px,transparent 1px);background-size:44px 44px}.card:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 73% 35%,rgba(69,229,240,.09),transparent 34%),radial-gradient(circle at 91% 62%,rgba(216,44,222,.11),transparent 38%)}.card:after{content:"";position:absolute;inset:0;border:1px solid rgba(255,255,255,.075);pointer-events:none}.shape{position:absolute;z-index:0;width:${art==='shape-v3.webp'?'510px':'650px'};height:auto;right:${art==='shape-v3.webp'?'-28px':'-126px'};top:${art==='shape-v3.webp'?'92px':'70px'};opacity:${art==='shape-v3.webp'?'.82':'.94'};filter:saturate(1.06) contrast(1.03)}.fade{position:absolute;z-index:1;inset:0;background:linear-gradient(90deg,#060509 0%,rgba(6,5,9,.98) 47%,rgba(6,5,9,.50) 72%,rgba(6,5,9,.04) 100%)}.spark{position:absolute;z-index:2;width:5px;height:5px;border-radius:50%;background:#e337dd;box-shadow:-970px 94px 0 #59dce9,-108px 430px 0 #5bceda;right:68px;top:88px}.top{position:relative;z-index:3}.logo{width:204px;height:auto;display:block}.content{position:absolute;left:54px;top:150px;width:720px;z-index:3}.eyebrow{font-family:Consolas,monospace;font-size:15px;text-transform:uppercase;letter-spacing:.28em;color:#67dfe8;font-weight:700;margin-bottom:24px}.eyebrow:before{content:"✣";color:#e23bdd;margin-right:12px}.headline{font-size:${headlineSize}px;line-height:1.08;letter-spacing:-.035em;font-weight:350;margin:0 0 22px;color:#f5f2ed;max-width:720px}.sub{font-size:25px;line-height:1.32;color:#63dce7;width:660px;margin:0;font-weight:350}.cta{position:absolute;left:54px;bottom:54px;z-index:3;background:#f6f5f4;color:#17151a;border-radius:16px;padding:15px 21px;font-size:15px;font-weight:750;box-shadow:0 0 0 1px rgba(255,255,255,.16)}.cta:after{content:"  →";font-size:18px}.site{position:absolute;right:54px;bottom:60px;z-index:3;color:#d7d3da;font-family:Consolas,monospace;font-size:14px;letter-spacing:.16em;text-transform:uppercase}.proof{position:absolute;left:54px;bottom:22px;z-index:3;color:#7f7985;font-family:Consolas,monospace;font-size:10px;letter-spacing:.16em;text-transform:uppercase}.proof b{color:#b8ff5e;font-weight:400}
  </style></head><body><div class="card"><img class="shape" src="../${art}"><div class="fade"></div><div class="spark"></div><div class="top"><img class="logo" src="../3sverse-logo.png"></div><div class="content"><div class="eyebrow">${esc(eyebrow)}</div><h1 class="headline">${esc(headline)}</h1><p class="sub">${esc(subhead)}</p></div><div class="cta">${esc(cta)}</div><div class="site">3sverse.com</div><div class="proof"><b>●</b> Free trial &nbsp;·&nbsp; No card &nbsp;·&nbsp; Windows 10/11</div></div></body></html>`;
  fs.writeFileSync(path.join(cardsDir, `day-${String(day).padStart(2,'0')}.html`), html);
}

let md = `# 3SVerse 30-Day LinkedIn Sales Campaign\n\n**Campaign dates:** October 1–30, 2026  \n**Primary audience:** VidaPay and Total Wireless retailers, owners, district managers, and multi-store operators  \n**Recommended posting time:** 9:00 AM Central Time  \n**Primary objective:** Convert operational pain into free-trial starts at [3sverse.com](https://3sverse.com)  \n\n## Positioning guardrails\n\n- Present 3SVerse as independent software for wireless dealers; do not imply affiliation with VidaPay or Total Wireless.\n- Lead with operator pain, demonstrate the workflow benefit, and close with one clear call to action.\n- Use only the current offer and pricing shown on 3sverse.com at posting time.\n- Reply to comments quickly and move qualified prospects to the free 7-day trial.\n\n## Search and campaign keywords\n\nVidaPay automation; Total Wireless retailer software; wireless dealer operations; multi-store wireless retail; incentive extraction; device ordering automation; rebate filing automation; Windows retail software; wireless retail back-office automation.\n\n`;

for (let i = 0; i < posts.length; i++) {
  const day = i + 1;
  const [headline, subhead, eyebrow, caption, cta, tags] = posts[i];
  const date = new Date(Date.UTC(2026, 9, day));
  md += `## Day ${day} — ${dateFmt.format(date)}\n\n![Day ${day}: ${headline}](images/day-${String(day).padStart(2,'0')}.png)\n\n**Campaign stage:** ${phases.find(p => day >= p.from && day <= p.to).label}  \n**Creative hook:** ${headline}  \n**CTA:** ${cta}\n\n${caption.replace('\n\n','\n\n')}\n\n${tags}\n\n---\n\n`;
}
fs.writeFileSync(path.join(root, '3SVerse-LinkedIn-Campaign-Oct-2026.md'), md);

const index = `<!doctype html><html><head><meta charset="utf-8"><title>3SVerse 30-Day LinkedIn Campaign</title><style>body{font-family:Segoe UI,Arial;background:#071126;color:#eaf0ff;margin:0;padding:40px}main{max-width:1050px;margin:auto}h1{font-size:42px}.meta{color:#a9b9dc}.post{background:#111d3d;margin:30px 0;padding:28px;border-radius:14px;border:1px solid #293861}.post img{width:100%;border-radius:8px}.caption{white-space:pre-line;font-size:18px;line-height:1.55}.tags{color:#52cdf2;font-weight:650}a{color:#5ee3ff}</style></head><body><main><h1>3SVerse 30-Day LinkedIn Sales Campaign</h1><p class="meta">October 1–30, 2026 • VidaPay / Total Wireless dealer operations • Recommended: 9:00 AM CT daily</p>${posts.map((p,i)=>`<section class="post"><h2>Day ${i+1} — ${esc(dateFmt.format(new Date(Date.UTC(2026,9,i+1))))}</h2><img src="images/day-${String(i+1).padStart(2,'0')}.png"><h3>${esc(p[0])}</h3><p class="caption">${esc(p[3])}</p><p><strong>CTA:</strong> ${esc(p[4])}</p><p class="tags">${esc(p[5])}</p></section>`).join('')}</main></body></html>`;
fs.writeFileSync(path.join(root, '3SVerse-LinkedIn-Campaign-Oct-2026.html'), index);

fs.writeFileSync(path.join(root, 'README.txt'), `3SVerse 30-Day LinkedIn Sales Campaign\r\nOctober 1–30, 2026\r\n\r\nOpen 3SVerse-LinkedIn-Campaign-Oct-2026.html for a visual campaign guide.\r\nOpen the Markdown file for easy copying/editing.\r\nReady-to-post 1200x627 PNG assets are in the images folder.\r\nSource card HTML and the exact supplied logo are in the source folder.\r\n`);
console.log(`Generated ${posts.length} cards and campaign documents in ${root}`);
